Active_Record_and_Action_Pack/week4/graded-assignments/todolists/config/routes.rb
Rails.application.routes.draw do
     
  root "todo_lists#index"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todo_lists do
    resources :todo_items
  end

  get  '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete "/logout",to: "sessions#destroy"

end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list, optional: true
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user, optional: true
  has_many :todo_items, dependent: :destroy
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/models/user.rb
class User < ApplicationRecord
  has_many :todo_lists, dependent: :destroy
  has_many :todo_items, through: :todo_lists, source: :todo_items, dependent: :destroy
  
  has_secure_password

  validates :username, presence: true

end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_login
  helper_method :logged_in?, :current_user

  protected

      def ensure_login
        redirect_to login_path unless logged_in?
      end

      def logged_in?
          session[:user_id] # nil is false
      end

      def current_user
          @current_user ||= User.find(session[:user_id])
      end
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :ensure_login, only: [:new, :create]

  
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:success] = "Logged in successfully"
        redirect_to root_path
    else
        flash[:danger] = 'Invalid username/password combination'
        redirect_to login_path
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: "You have been logged out"
  end

end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy]

  # # GET /todo_list/:todo_list_id/todo_items
  # # GET /todo_list/:todo_list_id/todo_items.json
  # def index
  #   @todo_items = TodoItem.all
  # end

  # GET /todo_list/:todo_list_id/todo_items/1
  # GET /todo_list/:todo_list_id/todo_items/1.json
  def show
  end

  # GET /todo_list/:todo_list_id/todo_items/new
  def new
    @todo_item = @todo_list.todo_items.new
  end

  # GET /todo_list/:todo_list_id/todo_items/1/edit
  def edit
  end

  # POST /todo_list/:todo_list_id/todo_items
  # POST /todo_list/:todo_list_id/todo_items.json
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_list/:todo_list_id/todo_items/1
  # PATCH/PUT /todo_list/:todo_list_id/todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to @todo_list, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_list/:todo_list_id/todo_items/1
  # DELETE /todo_list/:todo_list_id/todo_items/1.json
  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Todo item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:title, :due_date, :description, :completed)
    end

    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists.paginate(page: params[:page], per_page: 8)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:list_name, :list_due_date)
    end
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/helpers/application_helper.rb
module ApplicationHelper
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/helpers/sessions_helper.rb
module SessionsHelper
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolists</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <div style='float: right;'>
    Logged in as <%= current_user.username %> |
    <%= link_to "Logout", logout_path, method: :delete %> </div>
    <% end %>
    
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_items/_form.html.erb
<%= form_with(model: @todo_item, url: todo_item, local: true) do |form| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this @todo_item from being saved:</h2>

      <ul>
        <% @todo_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <% if !@todo_item.new_record?%>
  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_items/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form', todo_item: [@todo_list,@todo_item]%>

<%= link_to 'Show', todo_list_todo_item_path(@todo_list, @todo_item) %> |
<%= link_to 'Back', @todo_list %>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_items/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form', todo_item: [@todo_list,@todo_item] %>


<%= link_to 'Back', @todo_list %>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_item.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todo_item.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_item.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo_item.completed %>
</p>

<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list, @todo_item) %> |
<%= link_to 'Back', @todo_list %>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :list_name %>
    <%= form.text_field :list_name %>
  </div>

  <div class="field">
    <%= form.label :list_due_date %>
    <%= form.date_select :list_due_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>List name</th>
      <th>List due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.list_name %></td>
        <td><%= todo_list.list_due_date %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @todo_lists%>

<br>

<%= link_to 'New Todo List', new_todo_list_path %>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>

Active_Record_and_Action_Pack/week4/graded-assignments/todolists/app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List name:</strong>
  <%= @todo_list.list_name %>
</p>

<p>
  <strong>List due date:</strong>
  <%= @todo_list.list_due_date %>
</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list.todo_items.each do |todo_item| %>
      <tr>
        <td><%= todo_item.title %></td>
        <td><%= todo_item.due_date %></td>
        <td><%= todo_item.description %></td>
        <td><%= todo_item.completed %></td>
        <td><%= link_to 'Show', [@todo_list, todo_item] %></td>
        <td><%= link_to 'Destroy', [@todo_list, todo_item], method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Todo Item', new_todo_list_todo_item_path(@todo_list) %>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>