Introduction/week3/config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  # get 'greeter/hello'

  # SAME AS ABOVE
  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye'

  root 'courses#index'
  # You can have the root of your site routed with "root"
  # root 'welcome#index'
end

Introduction/week3/app/models/coursera.rb
class Coursera
  include HTTParty

  default_options.update(verify: false) # Turn off SSL verification
  base_uri 'https://api.coursera.org/api/catalog.v1/courses'
  default_params fields: "smallIcon,shortDescription", q: "search"
  format :json

  def self.for term
    get("", query: { query: term})["elements"]
  end
end

Introduction/week3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Introduction/week3/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  	@search_term = params[:looking_for] || 'jhu'
  	@courses = Coursera.for(@search_term)
  end
end

Introduction/week3/app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  	random_names = ["Alex", "Joe", "Michael"]
  	@name = random_names.sample
  	@time = Time.now
  	@times_displayed ||= 0
  	@times_displayed += 1
  end
end

Introduction/week3/app/helpers/courses_helper.rb
module CoursesHelper
end

Introduction/week3/app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    # time string in AM/PM format
	time.strftime("%I:%M%p")
  end
end

Introduction/week3/app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %></h1>

<table border="1">
  <tr>
  	<th>Image</th>
  	<th>Name</th>
  	<th>Description</th>
  </tr>
  <% @courses.each do |course| %>
    <tr class=<%= cycle('even', 'odd') %>>
      <td><%= image_tag(course["smallIcon"])%></td>
      <td><%= course["name"] %></td>
      <td><%= course["shortDescription"] %></td>
    </tr>
  <% end %>
</table>

Introduction/week3/app/views/greeter/goodbye.html.erb
<% random_names = ["Alex", "Joe", "Michael"] %>
<h1>Bye, <%= random_names.sample %></h1>

Introduction/week3/app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %></h1>
<p>The time now is <%= formatted_time(@time) %> </p>
<p>This page has been viewed <%= @times_displayed %> time(s)</p>

<p><%= link_to "Google", "http://www.google.com" %></p>
<p><%= link_to "Goodbye", greeter_goodbye_path %></p>

Introduction/week3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>